"""Initial migration

Revision ID: 3748925a5363
Revises: 
Create Date: 2024-10-12 04:35:11.157107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3748925a5363'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('executors',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appeals',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('ordel_id', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('executor_id', sa.UUID(), nullable=True),
    sa.Column('laptop_serial_number', sa.String(), nullable=False),
    sa.Column('laptop_firm', sa.String(), nullable=False),
    sa.Column('laptop_model', sa.String(), nullable=False),
    sa.Column('commission_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('customer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('ordel_id')
    )
    op.create_table('results',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('appeal_id', sa.UUID(), nullable=True),
    sa.Column('defect_photo_path', sa.String(), nullable=False),
    sa.Column('defect_coords', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeals.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('appeals')
    op.drop_table('executors')
    op.drop_table('customers')
    # ### end Alembic commands ###
